/*
 * AUTO-GENERATED by scripts/generate-cucumber-glue.mjs — do not edit by hand.
 * IDE-only step map so the "Cucumber (Official)" VS Code extension can match
 * steps defined in steps/accessibility.steps.ts (playwright-bdd's real runtime never
 * loads this file — see ai/playwright-bdd-style.md).
 * Regenerate with: npm run generate:cucumber-glue
 */

import { Then } from '@cucumber/cucumber';

Then("the page meets WCAG level {word}", function () {});
