/*
 * AUTO-GENERATED by scripts/generate-cucumber-glue.mjs — do not edit by hand.
 * IDE-only step map so the "Cucumber (Official)" VS Code extension can match
 * steps defined in steps/edit-flow.steps.ts (playwright-bdd's real runtime never
 * loads this file — see ai/playwright-bdd-style.md).
 * Regenerate with: npm run generate:cucumber-glue
 */

import { Given, When, Then } from '@cucumber/cucumber';

Given("the user opens the today page without an edit token", function () {});
Given("the user opens the app with a valid edit token", function () {});
Given("the user opens the app with an invalid edit token", function () {});
Given("the user opened the inline edit form for the morning part of the day", function () {});
When("the user clicks the edit button for the {word} part of the day", function () {});
When("the user types a change into the form", function () {});
When("the user clicks cancel", function () {});
Then("a read-only badge is shown", function () {});
Then("no edit buttons are shown", function () {});
Then("a logout button is shown", function () {});
Then("an edit button is shown for each part of the day", function () {});
Then("an edit button is shown for the note", function () {});
Then("an inline form titled {string} is shown", function () {});
Then("the form is closed", function () {});
Then("the morning part of the day still shows its original value", function () {});
