/*
 * AUTO-GENERATED by scripts/generate-cucumber-glue.mjs — do not edit by hand.
 * IDE-only step map so the "Cucumber (Official)" VS Code extension can match
 * steps defined in steps/flights.steps.ts (playwright-bdd's real runtime never
 * loads this file — see ai/playwright-bdd-style.md).
 * Regenerate with: npm run generate:cucumber-glue
 */

import { Given, Then } from '@cucumber/cucumber';

Given("the user opens the flights page", function () {});
Then("every flight shows its flight number", function () {});
Then("every flight shows its departure and arrival times with time zone", function () {});
Then("every flight shows its flight duration", function () {});
Then("each flight shows a Flightradar24 link that matches its own flight number", function () {});
Then("a flight that departs more than a few hours from now shows a \"not yet available\" placeholder for its gate and terminal", function () {});
Then("each flight shows a route link to Google Maps directions between its departure and arrival locations", function () {});
