/*
 * AUTO-GENERATED by scripts/generate-cucumber-glue.mjs — do not edit by hand.
 * IDE-only step map so the "Cucumber (Official)" VS Code extension can match
 * steps defined in steps/hotels.steps.ts (playwright-bdd's real runtime never
 * loads this file — see ai/playwright-bdd-style.md).
 * Regenerate with: npm run generate:cucumber-glue
 */

import { Given, Then } from '@cucumber/cucumber';

Given("the user opens the hotels page", function () {});
Then("every hotel shows its name", function () {});
Then("every hotel shows its stay dates", function () {});
Then("every hotel shows its check-in and check-out times", function () {});
Then("every hotel shows its address", function () {});
Then("every hotel shows its phone number", function () {});
Then("every hotel shows its booking number", function () {});
Then("each hotel shows an \"Open in Google Maps\" link for its address", function () {});
Then("each hotel shows a \"View on Booking.com\" link", function () {});
