/*
 * AUTO-GENERATED by scripts/generate-cucumber-glue.mjs — do not edit by hand.
 * IDE-only step map so the "Cucumber (Official)" VS Code extension can match
 * steps defined in steps/navigation.steps.ts (playwright-bdd's real runtime never
 * loads this file — see ai/playwright-bdd-style.md).
 * Regenerate with: npm run generate:cucumber-glue
 */

import { Given, When, Then } from '@cucumber/cucumber';

Given("the user opens the today page", function () {});
When("the user navigates to the trip overview", function () {});
When("the user navigates to the hotels page", function () {});
When("the user navigates to the flights page", function () {});
When("the user navigates back to the today page", function () {});
When("the user opens the photos page from the extra menu", function () {});
When("the user opens the practical information page from the extra menu", function () {});
When("the user visits every main page in sequence", function () {});
When("the user taps through every main section", function () {});
When("the user scrolls to the bottom of the page", function () {});
Then("the trip overview is visible", function () {});
Then("the hotels overview is visible", function () {});
Then("the flights overview is visible", function () {});
Then("the today page is visible", function () {});
Then("the photos page is visible", function () {});
Then("the practical information page is visible", function () {});
Then("no console errors should have occurred", function () {});
Then("each section is shown in turn", function () {});
Then("the bottom navigation does not overlap the page content", function () {});
