/*
 * AUTO-GENERATED by scripts/generate-cucumber-glue.mjs — do not edit by hand.
 * IDE-only step map so the "Cucumber (Official)" VS Code extension can match
 * steps defined in steps/photos.steps.ts (playwright-bdd's real runtime never
 * loads this file — see ai/playwright-bdd-style.md).
 * Regenerate with: npm run generate:cucumber-glue
 */

import { Given, Then } from '@cucumber/cucumber';

Given("the user opens the photos page", function () {});
Then("every day without photos shows the placeholder text {string}", function () {});
