/*
 * AUTO-GENERATED by scripts/generate-cucumber-glue.mjs — do not edit by hand.
 * IDE-only step map so the "Cucumber (Official)" VS Code extension can match
 * steps defined in steps/practical-information.steps.ts (playwright-bdd's real runtime never
 * loads this file — see ai/playwright-bdd-style.md).
 * Regenerate with: npm run generate:cucumber-glue
 */

import { Given, When, Then } from '@cucumber/cucumber';

Given("the user opens the practical information page", function () {});
Given("the practical information page has finished loading", function () {});
When("the user selects a different city in the weather selector", function () {});
When("the user enters an amount in the Peso field", function () {});
When("the user enters an amount in the Euro field", function () {});
Then("the 14-day weather forecast for that city is shown", function () {});
Then("the Euro field shows the correctly converted amount", function () {});
Then("the Peso field shows the correctly converted amount", function () {});
Then("the exchange rate date shown next to the converter matches today's date", function () {});
Then("the emergency information block is shown", function () {});
Then("the money information block is shown", function () {});
Then("the transport information block is shown", function () {});
Then("the getting-there information block is shown", function () {});
