/*
 * AUTO-GENERATED by scripts/generate-cucumber-glue.mjs — do not edit by hand.
 * IDE-only step map so the "Cucumber (Official)" VS Code extension can match
 * steps defined in steps/security.steps.ts (playwright-bdd's real runtime never
 * loads this file — see ai/playwright-bdd-style.md).
 * Regenerate with: npm run generate:cucumber-glue
 */

import { Given, When, Then } from '@cucumber/cucumber';

Given("the user requests the app over HTTPS", function () {});
When("the user reloads the page", function () {});
When("the user searches for a script-injection payload", function () {});
Then("the address bar no longer shows the edit token", function () {});
Then("edit access is still available", function () {});
Then("the address bar still does not show the edit token", function () {});
Then("no dialog is triggered by the search", function () {});
Then("no day matches the payload", function () {});
Then("the response sets Strict-Transport-Security", function () {});
