/*
 * AUTO-GENERATED by scripts/generate-cucumber-glue.mjs — do not edit by hand.
 * IDE-only step map so the "Cucumber (Official)" VS Code extension can match
 * steps defined in steps/today.steps.ts (playwright-bdd's real runtime never
 * loads this file — see ai/playwright-bdd-style.md).
 * Regenerate with: npm run generate:cucumber-glue
 */

import { Given, When, Then } from '@cucumber/cucumber';

Given("today's day card shows a flight summary", function () {});
Given("today's day card shows a hotel summary", function () {});
When("today's day card has no note entered", function () {});
When("the user clicks the flight summary", function () {});
When("the user clicks the hotel summary", function () {});
Then("the day card for today shows the destination", function () {});
Then("the day card for today shows the date", function () {});
Then("the day card for today shows a weather forecast", function () {});
Then("the day card for today shows a beach score", function () {});
Then("the day card shows a summary of that day's flight, when a flight is scheduled", function () {});
Then("the day card shows a summary of that day's hotel, when a hotel is booked", function () {});
Then("the morning part of the day shows its planned activity", function () {});
Then("the afternoon part of the day shows its planned activity", function () {});
Then("the evening part of the day shows its planned activity", function () {});
Then("the note field shows the placeholder text \"Geen notitie\"", function () {});
Then("the \"Open location in Google Maps\" link for today's card contains the destination as a search query", function () {});
Then("the flights page opens showing that flight's details", function () {});
Then("the hotels page opens showing that hotel's details", function () {});
Then("the header shows a countdown to the trip or shows that the trip has started", function () {});
Then("the header shows the current time", function () {});
Then("the header shows the next upcoming flight, when one is scheduled", function () {});
