/*
 * AUTO-GENERATED by scripts/generate-cucumber-glue.mjs — do not edit by hand.
 * IDE-only step map so the "Cucumber (Official)" VS Code extension can match
 * steps defined in steps/trip-overview.steps.ts (playwright-bdd's real runtime never
 * loads this file — see ai/playwright-bdd-style.md).
 * Regenerate with: npm run generate:cucumber-glue
 */

import { Given, When, Then } from '@cucumber/cucumber';

Given("the user opens the trip overview page", function () {});
When("the user switches to the destinations view", function () {});
When("the user switches to the calendar view", function () {});
When("the user refreshes the page", function () {});
When("the user searches for {string}", function () {});
Then("the timeline view is shown by default", function () {});
Then("the trip days are listed in chronological order", function () {});
Then("the trip days are grouped per destination", function () {});
Then("a compact list of dates and destinations is shown", function () {});
Then("the destinations view is still shown", function () {});
Then("each destination shows a \"Top activities on GetYourGuide\" link for that destination", function () {});
Then("only the days matching {string} remain visible in the timeline", function () {});
