/*
 * AUTO-GENERATED by scripts/generate-cucumber-glue.mjs — do not edit by hand.
 * IDE-only step map so the "Cucumber (Official)" VS Code extension can match
 * steps defined in steps/visual-regression.steps.ts (playwright-bdd's real runtime never
 * loads this file — see ai/playwright-bdd-style.md).
 * Regenerate with: npm run generate:cucumber-glue
 */

import { Then } from '@cucumber/cucumber';

Then("the today page matches its visual baseline", function () {});
Then("the trip overview page matches its visual baseline", function () {});
Then("the hotels page matches its visual baseline", function () {});
Then("the flights page matches its visual baseline", function () {});
Then("the practical information page matches its visual baseline", function () {});
